@startuml

!includeurl https://raw.githubusercontent.com/manuvai/plantuml-utils/master/class_diagram_utils.puml

!function point($n1, $n2, $sign, $text = "")
    
    !if ($texte == "")
        !return $n1 + $sign + $n2
    !else
        !return $n1 + $sign + $n2 + " : " + $text
    !endif
    
!endfunction

!function implements($node1, $node2)
    !return point($node1, $node2, "..|>", "<<implements>>")
!endfunction

<style>

.initial {
    BackgroundColor LightBlue
}

</style>

package res {
    package controler {
        abstract AbstractControler <<initial>> {
            +construct("AbstractControler(AbstractModel)")
            +{abstract} void("cliqueSur(int, int)")
            +{abstract} void("calculerStepSuivant()")
        }

        class Controler extends AbstractControler {
            -member(long, period)
            -{static} int(DELAYS_BEFORE_YIED)
            +void("cliqueSur(int, int)")
            +void("calculerStepSuivant()")
            +{static} member(TypeCase, "getNextTypeCase(TypeCase)")
        }
    }

    package vue {

        package observer {
            interface Observateur <<initial>> {
                +{abstract} void("update()")
            }

            interface Observable <<initial>> {
                +{abstract} void("addObservateur(Observateur)")
                +{abstract} void("removeObservateur(Observateur)")
                +{abstract} void("demandeMiseAjourVue()")

            }

        }
        
        class MouseListener <<extends MouseAdapter>> <<initial>> {
            int(x0)
            int(y0)
            int(x1)
            int(y1)
            int(cote)
            int(xDepart)
            int(yDepart)
            int(xArrive)
            int(yArrive)
            boolean(deuxiemeClic)

            +construct("MouseListener(AbstractControler)")
            +void("mousePressed(MouseEvent)")
            +void("updateDimension(int, int, int, int, int)")
            +boolean("alinterieur(int, int)")
            +int("numeroCaseColonne(int)")
            +int("numeroCaseLigne(int)")
        }

        class PanelJeu <<extends javax.swing.JPanel>> <<initial>> {
            -member(Graphics, cg)

            +construct("PanelJeu()")
            +construct("PanelJeu(Vue)")
            +void("paintComponent(Graphics)")
            +void("drawSouris(int, int, int)")
            +void("drawChat(int, int, int)")
            +void("drawCaseIn(int, int, int)")
            +void("drawCaseOut(int, int, int)")
            +void("drawCaseMur(int, int, int)")
            +void("drawCaseChemin(int, int, int)")
            +void("drawCaseFlecheHaut(int, int, int)")
            +void("drawCaseFlecheBas(int, int, int)")
            +void("drawCaseFlecheGauche(int, int, int)")
            +void("drawCaseFlecheDroite(int, int, int)")
        }

        class RessourcesImages <<initial>> {
            +{static} member(Image, CHAT)
            +{static} member(Image, SOURIS)
            +{static} member(Image, FLECHE)
            +{static} member(Image, CHEMIN)
            +{static} member(Image, MUR)
            +{static} member(Image, IN)
            +{static} member(Image, OUT)
            -construct("RessourcesImages()")
        }

        class Vue <<initial>> {
            +construct("Vue(AbstractModel, AbstractControler)")
            +void("dessinerJeu()")
        }
    }

    package model {

        package animal {

            class Animal implements Observateur {
                -int(x)
                -int(y)
                -int(xDir)
                -int(yDir)

                +construct("Animal(int, int)")
                +int("getX()")
                +void("setX(int)")
                +int("getY()")
                +void("setY(int)")
                +int("getxDir()")
                +void("setxDir(int)")
                +int("getyDir()")
                +void("setyDir(int)")
            }

            class Souris {

            }

            class Chat {

            }
            
        }

        package map {
            interface AnimalTypeString {
                
            }
            interface MapTileTypeString {

            }
            class MapAdapter {

            }
            class MapLoader {
                
            }
        }

        abstract AbstractModel <<initial>> {
            +construct("AbstractModel()")
            +{abstract} void("faireSeDeplacerLesAnimaux()")
            +{abstract} member(TypeCase, "getTypeCase(int, int)")
            +{abstract} member(Animal, "getTypeCase(int, int)")
            +{abstract} int("getLargeur()")
            +{abstract} int("getHauteur()")
            +{abstract} int("getNbSourisIn()")
            +{abstract} int("getNbSourisOut()")
            +{abstract} int("getNbFlecheUtilisee()")
            +{abstract} int("getNbFlecheMax()")
            +{abstract} boolean("partieTerminer()")
            +void("demandeMiseAjourVue()")
            +void("removeObservateur(Observateur)")
            +void("addObservateur(Observateur)")
        }

        class Model extends AbstractModel {

        }

        enum TypeCase <<initial>> {
            MUR
            IN
            OUT
            CHEMIN
            FLECHE_HAUT
            FLECHE_DROITE
            FLECHE_BAS
            FLECHE_GAUCHE
        }
    }
}

extends(Chat, Animal, up)
extends(Souris, Animal, up)

implements(Vue, Observateur)

AbstractControler -right- AbstractModel
AbstractModel o-- Observateur : list(Observateur, observateurs)

MouseListener -- AbstractControler
PanelJeu -- Vue : member(Vue, fenetre)
Model -- TypeCase : member("Map<Integer, Map[Integer, TypeCase]>", cases)
Model -- Animal : list(Animal, animaux)

Vue -- AbstractModel
Vue -- MouseListener
Vue -- AbstractControler

@enduml
