@startuml

!includeurl https://raw.githubusercontent.com/manuvai/plantuml-utils/master/class_diagram_utils.puml

!function point($n1, $n2, $sign, $text = "")
    
    !if ($texte == "")
        !return $n1 + $sign + $n2
    !else
        !return $n1 + $sign + $n2 + " : " + $text
    !endif
    
!endfunction

!function implements($node1, $node2)
    !return point($node1, $node2, "..|>", "<<implements>>")
!endfunction

<style>

.initial {
    BackgroundColor LightBlue
}

</style>

package res {

    !include inc/model.iuml
    !include inc/vue.iuml
    !include inc/controler.iuml

}

implements(Vue, Observateur)

AbstractControler -right- AbstractModel
MouseListener -- AbstractControler
PanelJeu -- Vue : member(Vue, fenetre)

Vue -- AbstractModel
Vue -- MouseListener
Vue -- AbstractControler

remove vue

@enduml
